#!/bin/bash
set -e

# Usage: ./scripts/create-worktree.sh <agent-name> [base-branch]
# Creates a persistent agent worktree in detached HEAD mode

AGENT_NAME=$1
BASE_BRANCH=${2:-main}

if [ -z "$AGENT_NAME" ]; then
    echo "Usage: $0 <agent-name> [base-branch]"
    echo "Example: $0 claude-alpha main"
    echo ""
    echo "Creates a persistent worktree for an agent in detached HEAD mode."
    echo "The agent will create feature branches when given tasks."
    exit 1
fi

# Get project paths
PROJECT_ROOT=$(git rev-parse --show-toplevel)
PROJECT_NAME=$(basename "$PROJECT_ROOT")
WORKTREE_CONTAINER="${PROJECT_ROOT}-worktrees"
WORKTREE_PATH="$WORKTREE_CONTAINER/$AGENT_NAME"
AGENTS_YAML="$WORKTREE_CONTAINER/agents.yaml"

# Ensure worktree container exists
mkdir -p "$WORKTREE_CONTAINER"

# Check if agent already exists
if [ -d "$WORKTREE_PATH" ]; then
    echo "Error: Agent worktree already exists at: $WORKTREE_PATH"
    exit 1
fi

# Function to get next available port
get_next_available_port() {
    local base_port=$1
    local port=$base_port

    if [ -f "$AGENTS_YAML" ]; then
        while grep -q "port: $port" "$AGENTS_YAML" 2>/dev/null; do
            port=$((port + 1))
        done
    fi

    echo "$port"
}

# Get next available ports
DEV_PORT=$(get_next_available_port 8001)
FRONTEND_PORT=$(get_next_available_port 3001)

# Create worktree in detached HEAD mode
echo "Creating agent worktree at: $WORKTREE_PATH"
git worktree add --detach "$WORKTREE_PATH" "$BASE_BRANCH"

# Register agent in agents.yaml
CREATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

if [ ! -f "$AGENTS_YAML" ]; then
    # Create new agents.yaml
    cat > "$AGENTS_YAML" <<EOF
# agents.yaml - Port assignments for active agent worktrees
# This file is auto-generated by create-worktree.sh
agents:
  $AGENT_NAME:
    worktree_path: $WORKTREE_PATH
    dev_port: $DEV_PORT
    frontend_port: $FRONTEND_PORT
    created: $CREATED_AT
EOF
else
    # Append to existing agents.yaml
    cat >> "$AGENTS_YAML" <<EOF
  $AGENT_NAME:
    worktree_path: $WORKTREE_PATH
    dev_port: $DEV_PORT
    frontend_port: $FRONTEND_PORT
    created: $CREATED_AT
EOF
fi

# Configure shared hooks path if it exists
if [ -d "/Users/medwards/Documents/git-hooks/python-tox" ]; then
    echo "Configuring shared git hooks..."
    cd "$WORKTREE_PATH"
    git config core.hooksPath /Users/medwards/Documents/git-hooks/python-tox
    cd "$PROJECT_ROOT"
fi

# Setup Python venv
echo "Setting up Python virtual environment..."
cd "$WORKTREE_PATH"
python3 -m venv .venv
source .venv/bin/activate

# Install dependencies (checks multiple possible configurations)
if [ -f "requirements.txt" ]; then
    echo "Installing from requirements.txt..."
    pip install -r requirements.txt
elif [ -f "pyproject.toml" ]; then
    echo "Installing from pyproject.toml..."
    pip install -e ".[dev]"
elif [ -f "setup.py" ]; then
    echo "Installing from setup.py..."
    pip install -e ".[dev]"
fi

# Install tox if needed
if command -v tox &> /dev/null; then
    pip install tox
fi

# Setup npm dependencies if frontend exists
if [ -f "package.json" ]; then
    echo "Installing npm dependencies..."
    npm install
fi

# Create environment configuration with auto-assigned ports
cat > .env.local <<EOF
# Agent-specific environment variables
AGENT_NAME=$AGENT_NAME
DEV_PORT=$DEV_PORT
FRONTEND_PORT=$FRONTEND_PORT
DATABASE_URL=sqlite:///./dev_${AGENT_NAME}.db
EOF

echo ""
echo "Agent worktree created successfully!"
echo "  Agent: $AGENT_NAME"
echo "  Path: $WORKTREE_PATH"
echo "  State: detached HEAD at $BASE_BRANCH"
echo "  Dev Port: $DEV_PORT"
echo "  Frontend Port: $FRONTEND_PORT"
echo ""
echo "To start working:"
echo "  cd $WORKTREE_PATH"
echo "  source .venv/bin/activate"
echo ""
echo "When given a task, create a branch:"
echo "  git checkout -b feature/my-task"
echo ""
